version: '3'

networks:
  ingaia-backend:
    driver:
      bridge

services:

  mongodb:
    image: mongo
    container_name: mongo-ingaia
    networks:
      - ingaia-backend

  node1:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: chulesantos/node-ingaia
    container_name: node-ingaia-1
    ports:
      - "3000"
    networks:
      - ingaia-backend
    depends_on:
      - "mongodb"

  node2:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: chulesantos/node-ingaia
    container_name: node-ingaia-2
    ports:
      - "3000"
    networks:
      - ingaia-backend
    depends_on:
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: chulesantos/node-ingaia
    container_name: node-ingaia-3
    ports:
      - "3000"
    networks:
      - ingaia-backend
    depends_on:
      - "mongodb"

  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: chulesantos/nginx-ingaia
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - ingaia-backend
    depends_on:
      - "node1"
      - "node2"
      - "node3"